// ###################################################

// DO NOT EDIT THIS FILE IT IS GENERATED AUTOMATICALLY

// ###################################################

package com.puritylake.lox.parsing;

import com.puritylake.lox.exceptions.*;

import java.util.List;

public abstract class Expr {
    public interface Visitor<R> {
        R visitAssignExpr(Assign expr) throws Exception;
;
        R visitBinaryExpr(Binary expr) throws Exception;
;
        R visitGroupingExpr(Grouping expr) throws Exception;
;
        R visitLiteralExpr(Literal expr) throws Exception;
;
        R visitLogicalExpr(Logical expr) throws Exception;
;
        R visitUnaryExpr(Unary expr) throws Exception;
;
        R visitCommaGroupExpr(CommaGroup expr) throws Exception;
;
        R visitTernaryExpr(Ternary expr) throws Exception;
;
        R visitVariableExpr(Variable expr) throws Exception;
;
    }
    public static class Assign extends Expr {
       public Assign(Token name, Expr value) {
            this.name = name;
            this.value = value;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) throws Exception {
            return visitor.visitAssignExpr(this);
        }

        final Token name;
        final Expr value;
    }
    public static class Binary extends Expr {
       public Binary(Expr left, Token operator, Expr right) {
            this.left = left;
            this.operator = operator;
            this.right = right;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) throws Exception {
            return visitor.visitBinaryExpr(this);
        }

        final Expr left;
        final Token operator;
        final Expr right;
    }
    public static class Grouping extends Expr {
       public Grouping(Expr expression) {
            this.expression = expression;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) throws Exception {
            return visitor.visitGroupingExpr(this);
        }

        final Expr expression;
    }
    public static class Literal extends Expr {
       public Literal(Object value) {
            this.value = value;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) throws Exception {
            return visitor.visitLiteralExpr(this);
        }

        final Object value;
    }
    public static class Logical extends Expr {
       public Logical(Expr left, Token operator, Expr right) {
            this.left = left;
            this.operator = operator;
            this.right = right;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) throws Exception {
            return visitor.visitLogicalExpr(this);
        }

        final Expr left;
        final Token operator;
        final Expr right;
    }
    public static class Unary extends Expr {
       public Unary(Token operator, Expr right) {
            this.operator = operator;
            this.right = right;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) throws Exception {
            return visitor.visitUnaryExpr(this);
        }

        final Token operator;
        final Expr right;
    }
    public static class CommaGroup extends Expr {
       public CommaGroup(Expr left, Expr right) {
            this.left = left;
            this.right = right;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) throws Exception {
            return visitor.visitCommaGroupExpr(this);
        }

        final Expr left;
        final Expr right;
    }
    public static class Ternary extends Expr {
       public Ternary(Expr cond, Expr trueVal, Expr falseVal) {
            this.cond = cond;
            this.trueVal = trueVal;
            this.falseVal = falseVal;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) throws Exception {
            return visitor.visitTernaryExpr(this);
        }

        final Expr cond;
        final Expr trueVal;
        final Expr falseVal;
    }
    public static class Variable extends Expr {
       public Variable(Token name) {
            this.name = name;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) throws Exception {
            return visitor.visitVariableExpr(this);
        }

        final Token name;
    }

    public abstract <R> R accept(Visitor<R> visitor) throws Exception;
}
