// ###################################################

// DO NOT EDIT THIS FILE IT IS GENERATED AUTOMATICALLY

// ###################################################

package com.puritylake.lox.parsing;

import java.util.List;

public abstract class Stmt {
    public interface Visitor<R> {
        R visitBlockStmt(Block stmt);
        R visitExpressionStmt(Expression stmt);
        R visitPrintStmt(Print stmt);
        R visitVarStmt(Var stmt);
    }
    public static class Block extends Stmt {
       public Block(List<Stmt> statements) {
            this.statements = statements;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitBlockStmt(this);
        }

        final List<Stmt> statements;
    }
    public static class Expression extends Stmt {
       public Expression(Expr expression) {
            this.expression = expression;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitExpressionStmt(this);
        }

        final Expr expression;
    }
    public static class Print extends Stmt {
       public Print(Expr expression) {
            this.expression = expression;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitPrintStmt(this);
        }

        final Expr expression;
    }
    public static class Var extends Stmt {
       public Var(Token name, Expr initializer, boolean initialized) {
            this.name = name;
            this.initializer = initializer;
            this.initialized = initialized;
        }

        @Override
        public <R> R accept(Visitor<R> visitor) {
            return visitor.visitVarStmt(this);
        }

        final Token name;
        final Expr initializer;
        final boolean initialized;
    }

    public abstract <R> R accept(Visitor<R> visitor);
}
